"""Static assertion that `.gitattributes` never references deleted packages.

PDFX-E001-F003 deleted `packages/api-client/` and the root JS workspace
(including `pnpm-lock.yaml`). Issue #408 caught that `.gitattributes`
still carried `linguist-generated=true` rules pointing at those paths —
GitHub silently ignores the rules because the paths do not exist, which
is invisible by design and exactly the kind of documentation rot a meta
test should pin.

This test enumerates the path prefixes referenced in `.gitattributes` and
asserts that every one of them either exists on disk or belongs to a
well-known generated-artifacts directory that the codegen task creates on
demand (i.e. `apps/backend/app/exceptions/_generated/`, which is
regenerated by `task errors:generate`).
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Final

from tests._paths import REPO_ROOT as _REPO_ROOT

# Matches the first glob metacharacter in a `.gitattributes` pattern.
# `.gitattributes` uses fnmatch-style globs, so `*`, `?`, and a `[` that
# opens a character class all terminate the literal path prefix. Splitting
# on this set (rather than only on `*`) avoids treating patterns such as
# `path/?name` or `path/[abc]dir/file` as literal filesystem paths.
_GLOB_METACHARS: Final[re.Pattern[str]] = re.compile(r"[*?\[]")

_GITATTRIBUTES: Final[Path] = _REPO_ROOT / ".gitattributes"

# Paths that are allowed to appear in `.gitattributes` even when they do
# not currently exist on disk — they are re-created by codegen or CI.
_GENERATED_ON_DEMAND: Final[frozenset[str]] = frozenset(
    {
        "apps/backend/app/exceptions/_generated",
    }
)


def _path_targets() -> list[tuple[int, str]]:
    """Return `(line_no, path_prefix)` for every non-comment `.gitattributes` rule.

    The pattern in a gitattributes line is the first whitespace-delimited
    token. Rules we check:

    - Anchored path rules (e.g. `packages/api-client/src/schema.d.ts` or
      `pnpm-lock.yaml`) — the prefix before any glob must exist on disk.
    - Extension-only rules (e.g. `*.png binary`) — skipped, they are
      content-type rules with no path component to verify. Patterns that
      begin with `*` but still contain a `/` (e.g. `**/pnpm-lock.yaml`)
      are *not* treated as extension-only — they fall through so their
      literal prefix (possibly empty) is still evaluated.
    - Deep globs (e.g. `apps/backend/app/exceptions/_generated/**`) — the
      directory prefix before the first glob metacharacter (`*`, `?`, `[`)
      is what we check.
    """
    targets: list[tuple[int, str]] = []
    for lineno, raw in enumerate(_GITATTRIBUTES.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        pattern = line.split(None, 1)[0]
        # Only skip truly content-type rules like `*.png binary`. Patterns
        # such as `**/pnpm-lock.yaml` or `*/foo/bar` still carry a path
        # component and must fall through to the prefix check so stale
        # path rules cannot slip through unnoticed.
        if pattern.startswith("*") and "/" not in pattern:
            continue
        # Root-anchored patterns (e.g. `/pnpm-lock.yaml`) must be treated as
        # relative to the repo root; without the strip, `_REPO_ROOT / prefix`
        # would evaluate to an absolute path and bypass the repo boundary.
        # We split on any glob metacharacter (`*`, `?`, `[`) — not just `*` —
        # so fnmatch-style patterns like `path/?name` or `path/[abc]/file`
        # yield the correct literal prefix instead of being treated as
        # literal filesystem paths.
        unanchored = pattern.removeprefix("/")
        prefix = _GLOB_METACHARS.split(unanchored, maxsplit=1)[0].rstrip("/")
        # Leading-glob patterns like `**/pnpm-lock.yaml` or `*/foo/bar` split
        # to an empty literal prefix. We cannot safely treat the empty string
        # as a filesystem path (every directory "exists" trivially), so they
        # fall through the prefix check. The dedicated
        # `test_gitattributes_no_leading_glob_patterns` assertion below pins
        # the invariant that no such patterns are in `.gitattributes` today —
        # if someone adds one, that test will fail loudly and prompt a
        # revision of this prefix-based strategy.
        if prefix:
            targets.append((lineno, prefix))
    return targets


def _raw_patterns() -> list[tuple[int, str]]:
    """Return `(line_no, pattern)` for every non-comment `.gitattributes` rule."""
    patterns: list[tuple[int, str]] = []
    for lineno, raw in enumerate(_GITATTRIBUTES.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        patterns.append((lineno, line.split(None, 1)[0]))
    return patterns


def test_gitattributes_paths_all_exist_or_are_generated() -> None:
    missing: list[str] = []
    for lineno, prefix in _path_targets():
        candidate = _REPO_ROOT / prefix
        if candidate.exists():
            continue
        # Allow prefixes that exactly match, or are nested beneath, a
        # generated-on-demand directory. This covers the "specific file
        # under a codegen directory" case because
        # `prefix.startswith(allowed + "/")` matches any file or deeper
        # directory beneath an allowed prefix.
        if any(
            prefix == allowed or prefix.startswith(allowed + "/")
            for allowed in _GENERATED_ON_DEMAND
        ):
            continue
        missing.append(f".gitattributes:{lineno} references missing path {prefix!r}")
    assert not missing, (
        "Stale paths in .gitattributes (the rule is a silent no-op because "
        "the path does not exist). Remove the line, or, if the path will be "
        "generated on demand, add its prefix to _GENERATED_ON_DEMAND in this "
        "test. Offenders:\n" + "\n".join(missing)
    )


def test_gitattributes_no_leading_glob_patterns() -> None:
    """Pin the invariant that no `.gitattributes` pattern starts with a glob.

    `_path_targets()` extracts the literal prefix before the first glob
    metacharacter and skips patterns whose prefix is empty (leading-glob
    patterns like `**/pnpm-lock.yaml` or `*/foo/bar`). Such patterns have
    no literal path component the existence check can validate, so they
    would slip past the primary assertion unnoticed.

    If this test fails because a legitimate leading-glob pattern was
    added, replace the prefix-based validation in `_path_targets()` with
    a strategy that resolves the pattern against the real file tree
    (e.g. `Path.rglob` or `pathspec.PathSpec.match_tree`) so stale
    leading-glob rules cannot hide behind the current check.
    """
    offenders: list[str] = []
    for lineno, pattern in _raw_patterns():
        # Extension-only rules (`*.png binary`) are content-type rules,
        # not path rules, and are legitimately outside this test's scope.
        if pattern.startswith("*") and "/" not in pattern:
            continue
        unanchored = pattern.removeprefix("/")
        literal_prefix = _GLOB_METACHARS.split(unanchored, maxsplit=1)[0].rstrip("/")
        if not literal_prefix:
            offenders.append(f".gitattributes:{lineno} leading-glob pattern {pattern!r}")
    assert not offenders, (
        "Found `.gitattributes` pattern(s) that begin with a glob "
        "metacharacter and carry a path component. The prefix-existence "
        "check in `_path_targets()` silently ignores them. Either remove "
        "the pattern or extend `_path_targets()` to validate leading-glob "
        "patterns against the real file tree. Offenders:\n" + "\n".join(offenders)
    )
