"""Static assertion that `.gitattributes` never references deleted packages.

PDFX-E001-F003 deleted `packages/api-client/` and the root JS workspace
(including `pnpm-lock.yaml`). Issue #408 caught that `.gitattributes`
still carried `linguist-generated=true` rules pointing at those paths —
GitHub silently ignores the rules because the paths do not exist, which
is invisible by design and exactly the kind of documentation rot a meta
test should pin.

This test enumerates the path prefixes referenced in `.gitattributes` and
asserts that every one of them either exists on disk or belongs to a
well-known generated-artifacts directory that the codegen task creates on
demand (i.e. `apps/backend/app/exceptions/_generated/`, which is
regenerated by `task errors:generate`).
"""

from __future__ import annotations

from pathlib import Path
from typing import Final

# parents[5] walks: this file -> meta/ -> unit/ -> tests/ -> backend/ ->
# apps/ -> repo root. Mirrors the convention used by sibling meta tests.
_REPO_ROOT: Final[Path] = Path(__file__).resolve().parents[5]
_GITATTRIBUTES: Final[Path] = _REPO_ROOT / ".gitattributes"

# Paths that are allowed to appear in `.gitattributes` even when they do
# not currently exist on disk — they are re-created by codegen or CI.
_GENERATED_ON_DEMAND: Final[frozenset[str]] = frozenset(
    {
        "apps/backend/app/exceptions/_generated",
    }
)


def _path_targets() -> list[tuple[int, str]]:
    """Return `(line_no, path_prefix)` for every non-comment `.gitattributes` rule.

    The pattern in a gitattributes line is the first whitespace-delimited
    token. Rules we check:

    - Anchored path rules (e.g. `packages/api-client/src/schema.d.ts` or
      `pnpm-lock.yaml`) — the prefix before any glob must exist on disk.
    - Bare-extension rules (e.g. `*.png binary`) — skipped, they are
      content-type rules with no path component to verify.
    - Deep globs (e.g. `apps/backend/app/exceptions/_generated/**`) — the
      directory prefix before the glob is what we check.
    """
    targets: list[tuple[int, str]] = []
    for lineno, raw in enumerate(_GITATTRIBUTES.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        pattern = line.split(None, 1)[0]
        if pattern.startswith("*"):
            # Bare-extension rules like `*.png binary` are content-type
            # rules, not path rules.
            continue
        # Root-anchored patterns (e.g. `/pnpm-lock.yaml`) must be treated as
        # relative to the repo root; without the strip, `_REPO_ROOT / prefix`
        # would evaluate to an absolute path and bypass the repo boundary.
        prefix = pattern.removeprefix("/").split("*", 1)[0].rstrip("/")
        if prefix:
            targets.append((lineno, prefix))
    return targets


def test_gitattributes_paths_all_exist_or_are_generated() -> None:
    missing: list[str] = []
    for lineno, prefix in _path_targets():
        candidate = _REPO_ROOT / prefix
        if candidate.exists():
            continue
        # Walk up to find a generated-on-demand ancestor. This already
        # covers the "specific file under a codegen directory" case,
        # because `prefix.startswith(allowed + "/")` matches any file or
        # deeper directory beneath an allowed prefix.
        if any(
            prefix == allowed or prefix.startswith(allowed + "/")
            for allowed in _GENERATED_ON_DEMAND
        ):
            continue
        missing.append(f".gitattributes:{lineno} references missing path {prefix!r}")
    assert not missing, (
        "Stale paths in .gitattributes (the rule is a silent no-op because "
        "the path does not exist). Remove the line, or, if the path will be "
        "generated on demand, add its prefix to _GENERATED_ON_DEMAND in this "
        "test. Offenders:\n" + "\n".join(missing)
    )
